filebeat.prospectors:
  - input_type: log
    paths:
      - /var/log/nginx/access.log
    tags: ["nginx_access"]
  - input_type: log
    paths:
      - /var/log/nginx/error.log
    tags: ["nginx_error"]
  - input_type: log
    paths:
      - /var/log/webapp/app.log
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after
    tags: ["webapp"]
output.logstash:
  hosts: ["logstash:5044"]
