filebeat.prospectors:
  - input_type: log
    paths:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
      - /var/log/nginx/sample.log
  - input_type: log
    paths:
      - /var/log/webapp/app.log
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after
output.logstash:
  hosts: ["logstash:5044"]
