version: '3'
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./volumes/nginx_logs:/var/log/nginx
    links:
      - webapp
      - logstash
  webapp:
    build: webapp
    container_name: webapp
    ports:
      - 5000:5000
    volumes:
      - ./webapp:/code
      - ./volumes/webapp_logs:/var/log
    links:
      - logstash
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    build: logstash
    container_name: logstash
    links:
      - elasticsearch
    expose:
      - "5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: kibana
    ports:
      - 8000:8000
    environment:
      SERVER_PORT: 8000
      XPACK_SECURITY_ENABLED: "false"
    links:
      - elasticsearch
  filebeat:
    build: filebeat
    container_name: filebeat
    volumes:
      - ./volumes/nginx_logs:/var/log/nginx
      - ./volumes/webapp_logs:/var/log/webapp
      - ./filebeat/filebeat.yml:/filebeat/filebeat.yml
    links:
      - logstash

volumes:
  esdata: {}
